services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey_data:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8083:8080"
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: postgres
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nat_website
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgres
volumes:
  valkey_data:
  postgres_data: