server:
  forward-headers-strategy: native

spring:
  threads:
    virtual:
      enabled: true
  application:
    name: nat1_website_api
  datasource:
    url: jdbc:postgresql://localhost:5432/nat_website
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

app:
  scheduler:
    interval-ms: 300000
  ai:
    base-url:
    api-key:
    model:
